### ISSUE TITLE
document feature request

### ISSUE THREAD

**Issue by jonneguyt** [methodds/stmInsights#14]
- [Currently the top 100 documents are displayed, it would be nice to use an interactive button to allow the user to set this number]

- [Currently there is no minimum threshold on estimated topic proportion for documents. It would be nice to set a minimum 'theta'] 

- [It is possible to display documents based on the condition that they have an estimated topic proportion in a different topic (using where in findthoughts)] 

Just jotting these down here such that I don't forget, if I find some time I may implement these at some point.

**Comment by cschwem2er** [comment]
Thanks! Good suggestions, feel free to implement them if you find the time.

**Comment by jonneguyt** [comment]
pull request #15 implements the first two bullet points

The third bullet point is harder to implement, as it is incompatible with the first. Once you condition on something, the threshold is no longer used. Implementing this will require some design decisions which require careful consideration (and time, which I don't have right now). Let me know if you want to close the issue or not.
