### ISSUE TITLE
Multiple interactions

### ISSUE THREAD

**Issue by anamaranda** [methodds/stmInsights#17]
Thanks for your R-package which I often use and find extremely helpful. I was wondering if you'd consider adding the possibility of having more than two moderators in the interactions plot. This would be quite handy for plotting moderators with more than 2 levels. Thank you!

**Comment by cschwem2er** [comment]
Glad to read that stminsights is helpful to you. At the moment I do not have the capacity to add n-way interactions. Feel free to give it a try on your own and send a pull request if you want! :)

**Comment by cschwem2er** [comment]
closing this as I don't have time for this right now and no PR happened
