### ISSUE TITLE
Problem in displaying STM document ID

### ISSUE THREAD

**Issue by ZackCzq** [methodds/stmInsights#19]
Hi, thanks for this awesome package. But I just met a problem when trying to inspect the documents in stminsights. The results are fine when I haven't done anything on it (pic1). When I chose to display "STM document ID" so I would trace them back in the original file, the documents just hide and I cannot inspect the results any more (pic2).

I am not sure if this is a bug or due to my wrong operation. Would appreciate it if any help could be provided. @cschwem2er 

![pic1](https://user-images.githubusercontent.com/64600030/83514651-92ff3c00-a4c3-11ea-897c-a8fad9c4525f.png)
![pic2](https://user-images.githubusercontent.com/64600030/83514660-94c8ff80-a4c3-11ea-8e48-722ccff6013f.png)

**Comment by cschwem2er** [comment]
Thanks for posting this. The first think I would check is your R console running in the background while using stminsights. Does it show any warnings or error messages that might be related to the problem? In addition, I am tagging @jonneguyt here as he implemented the document ID feature and might have any idea what is going on.

**Comment by ZackCzq** [comment]
> Thanks for posting this. The first think I would check is your R console running in the background while using stminsights. Does it show any warnings or error messages that might be related to the problem? In addition, I am tagging @jonneguyt here as he implemented the document ID feature and might have any idea what is going on.

Thank you for reply. It did show warning as follow:
`Warning: Error in data.frame: arguments imply differing number of rows: 100, 24`

So I found that I needed to first change the required number to no more than the exact number of docs under this topic. Then it could work again.

**Comment by jonneguyt** [comment]
It sounds like it should be fixable. This behavior did not pop up before. Given that you found a workaround and I'm currently busy with other things, I will leave this open and come back to it later.
