### ISSUE TITLE
Feature request: Download R code used to reproduce the plots

### ISSUE THREAD

**Issue by lambdamoses** [methodds/stmInsights#21]
Thanks for the package. It would be nice to be able to save the R code used to make the plots in the shiny app to make the plots more reproducible, just like in `iSEE`.

**Comment by cschwem2er** [comment]
This is great idea. Right now I do not have spare time to implement this, but feel free to give it a try and submit a pull request! :)

**Comment by cschwem2er** [comment]
Closed due to inactivity.
