### ISSUE TITLE
What does content parameter do?

### ISSUE THREAD

**Issue by jooyoungseo** [methodds/stmInsights#22]
Thanks very much for developing such a nice package.

Would you mind addressing the following question at your best convenience?

According to your [`README` example](https://github.com/cschwem2er/stminsights/blob/master/README.md), there are two STM models: `poli` with `K = 20`; `poli_content` with `K = 15`.

However, I have noticed that `poli_content` has additional parameter `content` set to a covariate factor `~ rating`.

Is there any difference between a stm model with and without the `content` parameter?

I am asking this because it was not easy for me to understand the purpose of the `content` parameter when the `prevalence` (covariate formula) had been already specified.

Please advise me.

**Comment by cschwem2er** [comment]
Hi,

>  Is there any difference between a stm model with and without the content parameter?

Yes, there is a substantial difference. To quote from the [STM vignette](https://github.com/bstewart/stm/blob/master/vignettes/stmVignette.pdf?raw=true):

> Topical prevalence refers to how much of a document is associated with a topic and topical content refers to the words used within a topic. Hence metadata that explain topical prevalence are referred to as topical prevalence covariates, and variables that explain topical content are referred to as topical content covariates. It is important to note, however, that the model allows using topical prevalence covariates, a topical content covariate, both, or neither.

I would recommend you to spend some time reading the vignette to get a better understanding for the types of STM models you can fit. In addition, here is a lot of additional literature on stm: http://www.structuraltopicmodel.com/
