### ISSUE TITLE
pointestimate plots axis flips randomly

### ISSUE THREAD

**Issue by mhines-usgs** [methodds/stmInsights#23]
In analyzing a lot of documents by year, I'm exploring the topics with year on the y axis and proportion on the bottom with pointestimate, and moving from topic to topic, it seems to randomly flip the year axis direction from low to high or high to low. Do you have a suggestion on a way to make it more consistent behaving? Any tricks or? 

ex:
![image](https://user-images.githubusercontent.com/6920344/138960077-1023a593-87c1-4bd6-8c26-329e01bcfc0e.png)

then next plot of a diff topic but everything else the same:
![image](https://user-images.githubusercontent.com/6920344/138960107-17849f8b-8dca-4c0e-b90b-20a8c3fe567e.png)

**Comment by mhines-usgs** [comment]
the more i look at it i realize thats the only way it could work I guess given the proportions values 🙃

**Comment by cschwem2er** [comment]
Hi, in any case, you may want to consider a "continuous" rather than a "point estimate" plot for a variable such as "year" :)

**Comment by mhines-usgs** [comment]
thanks, yes, I've definitely been loving those :) just looking for more exploration options to share with others. 🍻
