### ISSUE TITLE
Upload files from the cloud into the shiny app

### ISSUE THREAD

**Issue by srosh2000** [methodds/stmInsights#25]
I am currently working on a project where I use STM for analysis on a virtual machine. When I run stminsights the shiny app is launched but when I click on `browse` to upload the .RData file it takes me to my local machine but the file exists on the cloud. Is there a way I can specify the exact directory where the file is located to upload it from the VM? 

Thanks in advance!

**Comment by cschwem2er** [comment]
Hi, I'm afraid that this is not possible. The only way I could see is if you were able to somehow connect your local file system to that of your cloud system, e.g. mapping the cloud server as a network drive. How to do that depends on your specific cloud and OS setup, but might be worth a try.

**Comment by srosh2000** [comment]
Hi, 
I have a little update on a workaround I found, in case this might be useful info for you too:
After cloning the repo one could edit the app.R somewhere around line 715 by changing 

load(infile$datapath, .GlobalEnv)

to

load('~/analyse-me.RData', .GlobalEnv)

 

"~/analyse-me.RData" being the file that you actually want to analyse.

And one can have an empty .RData file in their local machine which they upload using the browse button just to trigger the analysis but the file based on the hardcoded filepath will be uploaded anyway.
