### ISSUE TITLE
error installing stminsights

### ISSUE THREAD

**Issue by MariaYR** [methodds/stmInsights#6]
Hey there, 

Just tried installing stminsights from your repo and got the following: 

> library(stminsights)
Error: package or namespace load failed for ‘stminsights’:
 object ‘scale_type’ is not exported by 'namespace:ggplot2'. 

Is there a work around?

**Comment by cschwem2er** [comment]
Hi :)

I think this is a dependency issue. Could you please try to re-install? I updated the ggplot2 dependency to version 3.0.0.

**Comment by MariaYR** [comment]
solved! Thanks =)
