### ISSUE TITLE
Feature / enhancement request

### ISSUE THREAD

**Issue by jonneguyt** [methodds/stmInsights#8]
Firstly, thanks for the amazing package!

I mainly work with newspaper articles. Would it be possible to inspect multiple aspects of the corpus at the same time? Currently I can inspect (e.g.) the text, but I also have information on the title, the date, and other parts (e.g. which newspaper). It would be very useful if I could inspect several pieces of information simultaneously (I guess a table would work well). Let me know if there's any way in which I can help, although my coding skills are very (if not severely) limited

**Comment by cschwem2er** [comment]
Hi, 
you can inspect anything that is included as a variable in your meta dataset ``out$meta``:

![image](https://user-images.githubusercontent.com/7460499/45917173-025d0580-be72-11e8-9254-90eea45f6ff0.png)

**Comment by jonneguyt** [comment]
Hi Carsten,

Thanks for the quick reply. I know, but I was hoping to expect several things simultaneously (such that I can for example see the text of the article and title simultaneously, which are separate variables in my meta). Is there any way to do so?

**Comment by cschwem2er** [comment]
Ok, I just tried to implement this. Can you please reinstall stminsights from github and see whether the selection of multiple variables works for you?

**Comment by jonneguyt** [comment]
This is excellent!! Even the formatting works well. Thanks, didn't expect such a quick turnaround! We will make sure to cite/promote this package!
