### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by jonneguyt** [methodds/stmInsights#9]
Thanks again for the great package. After extensive usage, there are a few things which would have been great to while analyzing stm output.

In addition to #8, would it be possible to extend the inspection of relevant documents in three (minor) ways?

1. Include an additional column that indicates the proportion for the selected topic (perhaps optional via a check-box, to allow for users to (not) select it).
2. Extend the options to display up to 50 documents (perhaps 1, 5, 10, 50)
3. Include a row index column, to keep track of which document is being inspected

I hope that these changes are all relatively minor. Would very much appreciate if these can be implemented, if it helps I'd be happy to test-run things!

Thanks again!

**Comment by cschwem2er** [comment]
Hi,

thanks for suggesting new features for the app.

> Include an additional column that indicates the proportion for the selected topic (perhaps optional via a check-box, to allow for users to (not) select it).

I'm not sure how useful this would be as topic proportions can also be viewed in the "Proportions" and "Misc." dashboard. I consider it if implementation would be easy

> Include an additional column that indicates the proportion for the selected topic (perhaps optional via a check-box, to allow for users to (not) select it).
Should be possible, I'll look into it.

> Include a row index column, to keep track of which document is being inspected
Should also be possible, although I would have to make sure that these are consistent.

I'm a little busy at the moment, but I will get back to this when I find the time.

**Comment by jonneguyt** [comment]
Thanks for the reply, a quick clarification on one of the requests (1):

> I'm not sure how useful this would be as topic proportions can also be viewed in the "Proportions" and "Misc." dashboard. I consider it if implementation would be easy

It would be useful if it displayed the proportion for the article **itself** (the theta, along which - presumedly - you already sort the documents), rather than the total proportion of **all** articles assigned to the topic. 

> Extend the options to display up to 50 documents (perhaps 1, 5, 10, 50)
> Should be possible, I'll look into it.

Great! 

> Include a row index column, to keep track of which document is being inspected
> Should also be possible, although I would have to make sure that these are consistent.

Great, although I don't really understand the (potentially) consistency issues, happy to give more details about what I was thinking in case that'll help.

> I'm a little busy at the moment, but I will get back to this when I find the time.

No pressure, for our current project we are nearing the end, but planning on using the package in again in the future. Thanks again for the package - we really enjoyed working with it!

**Comment by jonneguyt** [comment]
I've implemented them on a local branch. I can't seem to do a pull request given that I'm not authorized to do so, what's the best way to submit a pull request?

**Comment by cschwem2er** [comment]
Cool, thanks for contributing! You should not need special authorization for submitting a PR. Have you checked this tutorial?
https://help.github.com/articles/creating-a-pull-request/

**Comment by jonneguyt** [comment]
Had to fork it in order to push from my local machine, which I did not know. One experience richer!

Please let me know if you like the way I implemented them, especially aesthetically. Happy to change/update, but given that I think any changes will be minor, feel free to just adjust my pull request!

**Comment by cschwem2er** [comment]
The updated version with your contributions is now available on CRAN =)
